### PR TITLE
remove getDOMNode() for react 0.14

### LINKED ISSUE #5: React 0.14.0 refs changes
Hi!
React team have recently [released v0.14.0](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html) and it exposing refs to DOM components as the DOM node itself so we don't need call .getDOMNode() anymore to get access to DOM element.
this.refs.elemName already contains it.

My console is full of

> Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Packery`.

Please consider this and remove .getDOMNode() from sources.
Thanks in advance!

### PR DESCRIPTION
**Pull request by theolampert**
Fixes #5 for me, I guess you will need to move 0.1.9 to another branch though.

### CODE REVIEW

**Comment by eiriklv** [comment]
Add some readme about the breaking changes - [see react-masonry-mixin](https://github.com/eiriklv/react-masonry-mixin) - and I'll merge it and bump the npm version :-)

**Comment by theolampert** [comment]
Ah I didn't see that!, would you prefer me to switch it to the same fallback you're using in the masonry version?.

**Comment by eiriklv** [comment]
Actually - this is fine

**Comment by eiriklv** [comment]
Thanks for the pull! :-)

If something breaks then just send a new PR

**Comment by eiriklv** [comment]
@theolampert check out [react-packery-component](https://github.com/eiriklv/react-packery-component) if you want a component version :-) Just released it

**Comment by theolampert** [comment]
@eiriklv thanks!, will probably switch to it in the future.

**Pull request merged**
